name       : gtkdatabox3
version    : 1.0.0
release    : 2
source     :
    - https://master.dl.sourceforge.net/project/gtkdatabox3/gtkdatabox-1.0.0.tar.gz : 7add2cd8fb4209f3970dbd33f5238e25b43f6251e7534607bf926c7c6175e14b
license    : GPL-3.0-or-later
homepage   : https://gtkdatabox3.sourceforge.io
component  : programming.library
summary    : GtkDatabox3 is a gtk3 widget for live display of large amounts of fluctuating numerical data.
description: |
    GtkDatabox3 is a widget for live display of large amounts of fluctuating numerical data. This project intends to be a direct replacement for GtkDatabox, which stalled with GTK-2.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-docs.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
